### ISSUE TITLE
How to get current cell index which is displaying in front?

### ISSUE THREAD

**Issue by aaasifrz9** [sumitlni/LNICoverFlowLayout#6] opened 2017-03-15 09:06 UTC

**Comment by sumitlni** [comment] 2017-05-03 20:58
You could just measure the offset of current cell and calculate the row accordingly. As an example, this is the code I added to the existing demo code that comes with LNICoverFlowLayout. When you shake the phone/simulator it prints the (0-based) index of cell in front.

    
```
    func getCurrentRow() {
        let width = photosCollectionView.collectionViewLayout.collectionViewContentSize.width / CGFloat(photosCollectionView.numberOfItems(inSection: 0))
        
        let currentRow = photosCollectionView.contentOffset.x / width
        
        print("Currently we are displaying item number \(currentRow)")
    }
    
    override func motionEnded(_ motion: UIEventSubtype, with event: UIEvent?)  {
        if motion == .motionShake {
            getCurrentRow()
        }
    }

```
Hope this helps. Closing the issue as this is not a bug in the code.

**Closed as completed by sumitlni** 2017-05-03 20:58 UTC

**Comment by aaasifrz9** [comment] 2017-05-05 03:45
Thanks a lot.
