### ISSUE TITLE
if i add your framework i get this error

### ISSUE THREAD

**Issue by ArjunSa786** [sumitlni/LNICoverFlowLayout#1] opened 2016-07-29 08:31 UTC
its awesome .. 

but i get Duplicate interface definition for class 'Parse'

thnaks

**Comment by sumitlni** [comment] 2016-07-29 17:05
Hi Arjun, the framework does not use Parse anywhere. Are you sure this is an issue caused by the framework? If you are, please provide steps to recreate the issue.

**Comment by SmartContainer** [comment] 2016-07-29 17:25
Hi sumitlni
i am also have same issue.
 i am using objective c code parse framework .when i add your framework this error will show..if i remove your framework its working fine.

**Comment by sumitlni** [comment] 2016-07-31 23:22
@SmartContainer Do not use this with Objective C - if you are using Objective C you can use the original YRCoverFlowLayout . This is for Swift-only.

@ArjunSa786 there is no definition of "Parse" class in the entire app. Please provide steps to recreate this issue in a Swift app.

**Comment by sumitlni** [comment] 2016-08-05 18:12
As I have not received any response back from you, I tried to recreate the issue myself, by following these steps:
1. Created a new Swift Single View App
2. Initialized it to use CocoaPods and added "Parse" and "LNICoverFlowLayout"
3. Added a new UICollectionViewController and changed the layout to LNICoverFlowLayout
4. Mixed and matched code to initialize Parse and create a new PFObject at multiple places inside the code, including in AppDelegate and the custom UICollectionViewController class I had just created. There were no compilation errors at all.

I am closing this issue as I could not recreate it. Please check your code and let me know if you can recreate the issue starting from scratch. As I mentioned in my first comment, I have no dependencies or usage of Parse inside LNICoverFlowLayout.

**Closed as completed by sumitlni** 2016-08-05 18:12 UTC
